### ISSUE TITLE
Add-Annotation fontsize/color not working

### ISSUE THREAD

**Issue by Bennse666** [py-pdf/pypdf#2084]
So, I'm trying to build a system to add/edit/delete Annotations on PDF.
But the Annotations do not use the given fontsize nor fontcolor.
And when I set border_color to 000000 I don't get any Text either, just the white "Annotation-Area" (white because of the background-color).

```bash
$ python -m platform
macOS-12.6-x86_64-i386-64bit

$ python -c "import pypdf;print(pypdf.__version__)"
3.14.0
```

```python
def dec_to_hex(num):
    number = str(hex(int(num)))
    if number.startswith('0x'):
        number = number[2:]
    if number=='0':
        number='00'
    return number

def add_annotation_pdf(annotation, temp_file_path):
    r, g, b = annotation['rgb'].replace('(','').replace(')','').split(',')
    rgb_str = f'{dec_to_hex(r)}{dec_to_hex(g)}{dec_to_hex(b)}'
    
    reader = PdfReader(temp_file_path)
    page = reader.pages[annotation['page']]
    page.scale_to(annotation['overall_x'], annotation['overall_y'])
    writer = PdfWriter()
    writer.add_page(page)

    annot = AnnotationBuilder.free_text(
        text=annotation['note'],
        rect=(annotation['x1'], annotation['y1'], annotation['x2'], annotation['y2']),
        font='Arial',
        italic=True,
        bold=True,
        font_size=str(annotation['fontSize'])+'pt',
        font_color=rgb_str,
        background_color='ffffff',
        border_color='ffffff'
    )

    writer.add_annotation(page_number=annotation['page'], annotation=annot)

    with open(temp_file_path, 'wb') as pdf_obj:
        writer.write(pdf_obj)
```

No Traceback Error
As for the PDF(s).. it's for every PDF

**Comment by Bennse666** [comment]
Quick Info:
changing border_color ALSO influences font_color, but font_color is not being used at all (it's being ignored)

**Comment by kang0410** [comment]
I've got the same issue so am following.

**Comment by Fellow-Bennse** [comment]
Any update on this matter?

@kang0410 for me it's not related to default viewer as I am not even using the preview-app.
I am using the function(s) for a webbased application where it also shows the PDF. After creating the Stamp/Annotation on the document, we use another library to create an image of the annotated page, and even there the Stamp/Annotation is not being formatted/displayed correctly.

**Comment by kang0410** [comment]
@Fellow-Bennse - Strange, have you tried opening the document in Acrobat reader (both after the stamp/annotation and after the other library to create an image)

**Comment by Fellow-Bennse** [comment]
@kang0410 Yea I did, and the annotations are missing Font-Size and Font-Color
When I set Border-Color to White (because of me not wanting a Border), then the Text is also white, since it uses the Border-Color for the Font for whatever reason

**Comment by Fellow-Bennse** [comment]
I would really appreciate it if it could be looked into..

**Comment by Fellow-Bennse** [comment]
@stefan6419846 
Hey Hey, yea I swapped back to `from pypdf.annotations import FreeText` because of the deprecation-warning

Showing the issue is a little hard when the annotations font-color is the same as border-color, meaning if I set Border-color to ffffff (white), I am also unable to see the text)

As for font-size it's kinda the same thing. If I put it 50, it's still default-size from the library, hard to like, you know, properly show it.

As for executable code:
`
from pypdf.annotations import FreeText

reader = PdfReader('your_pdf_path')
page = reader.pages[0]
page.scale_to(1600, 2300)
writer = PdfWriter()
writer.add_page(page)

annot =FreeText(
        text='Test-Text,
        rect=(50, 1700, 200, 1500),
        font='Arial',
        italic=True,
        bold=True,
        font_size='30pt',
        font_color='eeeeee',
        background_color='ffffff',
        border_color='ffffff'
    )
    
    writer.add_annotation(page_number=0, annotation=annot)

    with open('your_pdf_path', 'wb') as pdf_obj:
        writer.write(pdf_obj)
    `

**Comment by ilyaZar** [comment]
I have the exact same issue. `border_color` overwrites `font_color`, when "white" is specified as above nothing occurs (the font ending up in white as above). If not setting `border_color` at all then I cannot set `font_color` to anything different since the class default value field of `border_color` is used instead (which is black), so one always ends up with the same border and font color.

**Comment by ivoras** [comment]
I have the same problem: font_color is ignored in favor of border_color, and font_size is completely ignored.

**Comment by ilyaZar** [comment]
Maybe as a reproducible error @stefan6419846 , you can just look at the documentation https://pypdf.readthedocs.io/en/latest/user/adding-pdf-annotations.html#free-text where the snippet

```python
# Create the annotation and add it
annotation = FreeText(
    text="Hello World\nThis is the second line!",
    rect=(50, 550, 200, 650),
    font="Arial",
    bold=True,
    italic=True,
    font_size="20pt",
    font_color="00ff00",
    border_color="0000ff",
    background_color="cdcdcd",
)
```

indicates the use of different colors (`font_color="00ff00"` and `border_color="0000ff"`) but both is displayed in blue...

![image](https://github.com/py-pdf/pypdf/assets/36898027/a1bb40e0-8976-4cd2-b76e-2ded441ee53e)

**Comment by stefan6419846** [comment]
Should be fixed by #2893.

**Comment by raffaelemancuso** [comment]
> Should be fixed by [#2893](https://github.com/py-pdf/pypdf/pull/2893).

I don't think it is. I'm using 6.0.0 and still experience this issue (see bug I opened)
