### ISSUE TITLE
Image handling: Mode from RGB path will always be overwritten

### ISSUE THREAD

**Issue by stefan6419846** [py-pdf/pypdf#3367]
We have the following section for image mode retrieval: https://github.com/py-pdf/pypdf/blob/d9649d0d5f22c2710da238aa555c7dfdf8ff6eb3/pypdf/_xobj_image_helpers.py#L348-L375

As far as I can tell from the execution flow, the value of line 356 will always be overwritten by the following conditions.

The offending change is https://github.com/py-pdf/pypdf/commit/68e2cf0c25961f8ae5277dfc9ffa8978c00e3305#diff-185702ddcfbf2e4a9ef7106622bb77505eacae032966bba39c65ffb9cd0f9bc7L667 from #1834.

We should check whether this causes any harm and evaluate a fix with a corresponding fix.

**Comment by nevin-lim** [comment]
Hi there, my team and i would like to work on this issue if that is alright with you?

**Comment by stefan6419846** [comment]
No need to ask for permission to work on issues as long as there is no reason like somebody already having indicated working on it beforehand and actually having made progress.

**Comment by RavSinghChandan** [comment]
This should be resolved by #3938, which moved the low-bit expansion out
of _handle_flate into _expand_low_bit_samples() and calls it from all
three paths that build an image from raw bytes.

Verified on current main: an unfiltered 4-bit /DeviceRGB image now
resolves to mode "RGB" with samples expanded to the full 0-255 range,
rather than the mode being overwritten.

Happy to close if you agree.

**Comment by stefan6419846** [comment]
No, this is still an issue, as the following `if ... else` construction always sets a new mode without looking into the RGB value: https://github.com/py-pdf/pypdf/blob/main/pypdf/generic/_image_xobject.py#L478-L505
